// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Async = require("serbet/src/Async.bs.js");
var Serbet = require("serbet/src/Serbet.bs.js");
var HelloJsonEndpoint = require("./HelloJsonEndpoint.bs.js");

function saveUserInDatabase(_user) {
  return Async.async({
              TAG: /* Ok */0,
              _0: undefined
            });
}

function processUser(user) {
  return Async.async({
              id: user.id + 2 | 0,
              email: user.email
            });
}

function newUser(param) {
  return Async.async({
              id: 1,
              email: "hey papa"
            });
}

var hello = Serbet.endpoint(undefined, {
      path: "/",
      verb: /* GET */0,
      handler: (function (_req) {
          return Async.let_(Async.async({
                          id: 1,
                          email: "hey papa"
                        }), (function (user) {
                        return Async.async({
                                    TAG: /* OkString */3,
                                    _0: user.email
                                  });
                      }));
        })
    });

var app = Serbet.application(undefined, {
      hd: hello,
      tl: {
        hd: HelloJsonEndpoint.endpoint,
        tl: /* [] */0
      }
    });

exports.saveUserInDatabase = saveUserInDatabase;
exports.processUser = processUser;
exports.newUser = newUser;
exports.hello = hello;
exports.app = app;
/* hello Not a pure module */
